language: node_js
node_js:
 - "8.11.1"
 - "9.11.1"
 - "10.1.0"
 - "11"
script:
 - npm run-script build
 - npm run-script coverage
 - npm run-script lint
notifications:
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MEhhbGYtU2hvdCUzQWhhbGYtc2hvdC51ay8lMjFxUE5PblVzTnNaclRvRlpxeEIlM0FoYWxmLXNob3QudWs"
        on_success: change  # always|never|change
        on_failure: always
        on_start: never
