bridge:
  domain: "localhost"
  homeserverUrl: "http://localhost:8008"
  presenceInterval: 500
  disablePresence: false
  disableTypingNotifications: false
  disableDiscordMentions: false
  disableDeletionForwarding: false
  enableSelfServiceBridging: false
auth:
  clientID: "12345" # Get from discord
  secret: "blah"
  botToken: "foobar"
logging:
  console: "warn" #silly, verbose, info, http, warn, error, silent
  lineDateFormat: "MMM-D HH:mm:ss.SSS" # This is in moment.js format
  files:
    - file: "debug.log"
      disable:
        - "PresenceHandler" # Will not capture presence logging
    - file: "warn.log" # Will capture warnings
      level: "warn"
    - file: "botlogs.log" # Will capture logs from DiscordBot
      level: "info"
      enable: 
        - "DiscordBot" 
database:
  filename: "discord.db"
room:
  defaultVisibility: "public"
