bridge:
  domain: "localhost"
  homeserverUrl: "http://localhost:8008"
  presenceInterval: 500
  disablePresence: false
  disableTypingNotifications: false
  disableDiscordMentions: false
  disableDeletionForwarding: false
  enableSelfServiceBridging: false
auth:
  clientID: "12345" # Get from discord
  secret: "blah"
  botToken: "foobar"
logging:
  level: "warn" #silly, verbose, info, http, warn, error
database:
  filename: "discord.db"
room:
  defaultVisibility: "public"
